# Generated by Django 4.1.4 on 2023-01-18 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_homework'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
