# Generated by Django 4.1.4 on 2023-01-25 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_categoryprog_prog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='cat',
        ),
        migrations.DeleteModel(
            name='CategoryProgram',
        ),
        migrations.DeleteModel(
            name='Program',
        ),
    ]
