# Generated by Django 4.1.4 on 2023-01-25 12:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_remove_program_cat_delete_categoryprogram_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryprog',
            options={'ordering': ['id'], 'verbose_name': 'Категорию програмы', 'verbose_name_plural': 'Категории программ'},
        ),
        migrations.AlterModelOptions(
            name='prog',
            options={'ordering': ['time_create', 'title'], 'verbose_name': 'Программа', 'verbose_name_plural': 'Программы'},
        ),
        migrations.AddField(
            model_name='prog',
            name='registration',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
