# Generated by Django 4.1.4 on 2023-01-25 12:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_alter_categoryprog_options_alter_prog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prog',
            name='registration',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
